課題3. ストップウォッチ機能が利用できるアプリを作成する
retail-oukaku/flutter_study pull request #16
Opened 2023-06-07 06:45 UTC by retail-oukaku

2023-06-08 01:04 UTC, fujiki-yuya reviewed
@retail-oukaku 
特に問題ないと思いますが、ストップウォッチの実行中に数字がぶれて見えるので修正してみると良いかと思います。TextStyleを修正すれば解決できると思います。
その他は石渡さんからレビューをもらってください🙇‍♂

2023-06-08 06:00 UTC, retail-oukaku commented
> @retail-oukaku 特に問題ないと思いますが、ストップウォッチの実行中に数字がぶれて見えるので修正してみると良いかと思います。TextStyleを修正すれば解決できると思います。 その他は石渡さんからレビューをもらってください🙇‍♂

修正しました。
[数字がぶれてる問題を修正](https://github.com/retail-oukaku/flutter_study/pull/16/commits/74348577cf67618c211da537878905c35bad7f6b)

2023-06-09 14:48 UTC, MinatoIshiwata commented on lib/kadai3/stop_watch_page.dart
> +    );
こちらfinalで置く必要性がなさそうですが、なにか理由ございますでしょうか？

2023-06-09 14:48 UTC, MinatoIshiwata commented on lib/kadai3/stop_watch_page.dart
> +  Widget _buildListCellWidget(int index,String? itemText){
```suggestion
  Widget _buildListCellWidget(int index, String? itemText){
```

2023-06-09 14:55 UTC, MinatoIshiwata commented on lib/kadai3/stop_watch_page.dart
> +    return str.substring(0,str.length - 4);
マジックナンバになっているので数字に命名しましょう🙋

2023-06-09 14:55 UTC, MinatoIshiwata commented on lib/main.dart
> +              },),);
フォーマットがおかしいです🙋

2023-06-09 15:15 UTC, MinatoIshiwata requested changes
@retail-oukaku 
何点かコメント入れました🙋
ご確認のほどよろしくお願いいたします。

2023-06-12 00:11 UTC, retail-oukaku commented on lib/kadai3/stop_watch_page.dart
> +  Widget _buildListCellWidget(int index,String? itemText){
[space](https://github.com/retail-oukaku/flutter_study/pull/16/commits/4ff313ff6aea5a1fd60fb991d728bb90f024a05a)　を追加しました。

2023-06-12 00:13 UTC, retail-oukaku commented on lib/main.dart
> +              },),);
最新developのマージで、フォーマットを修正しました。

2023-06-12 00:19 UTC, retail-oukaku commented on lib/kadai3/stop_watch_page.dart
> +    return str.substring(0,str.length - 4);
修正しました。
[ローカル変数名をelapsedNumberに修正](https://github.com/retail-oukaku/flutter_study/pull/16/commits/e09aa3d0155a5246b7c0410092fe51102c512d05)

2023-06-12 01:19 UTC, retail-oukaku commented on lib/kadai3/stop_watch_page.dart
> +    );
[prefer_final_fields](https://dart-lang.github.io/linter/lints/prefer_final_locals.html)
ローカル変数なので、finalで宣言します。UI作成してる時、ローカル変数を使って、UIを速く調整できるためです。

2023-06-12 01:20 UTC, retail-oukaku commented on lib/kadai3/stop_watch_page.dart
> +    );
ローカル変数を削除しました。
[ローカル変数を削除](https://github.com/retail-oukaku/flutter_study/pull/16/commits/8aaa24895c2ce65c11caae1e112d5928be3f5380)

2023-06-12 16:50 UTC, MinatoIshiwata approved these changes
LGTM

2023-06-12 23:53 UTC, merged