Feature/kadai4
retail-oukaku/flutter_study pull request #17
Opened 2023-06-12 06:48 UTC by retail-oukaku

編集中

2023-06-12 16:51 UTC, MinatoIshiwata commented on lib/extensions/string_extension.dart
> +    }
dartの標準機能でasMap()やentriesやreduceなどを利用するともう少しスッキリするかと思います🙋

2023-06-12 16:52 UTC, MinatoIshiwata reviewed
@retail-oukaku 
1箇所ご確認のほどよろしくお願いいたします🙋

2023-06-14 18:25 UTC, MinatoIshiwata commented on lib/kadai4/barcode_scan_page.dart
> +                      alignment: Alignment.center,
@retail-oukaku 
Alignで良いかと思います

2023-06-14 18:27 UTC, MinatoIshiwata requested changes
@retail-oukaku 
コメントつけました。
ご確認のほどよろしくお願いいたします。

2023-06-15 00:09 UTC, retail-oukaku commented on lib/kadai4/barcode_scan_page.dart
> +              builder: (BuildContext context) {
テストコードです、削除しました。
[builderを削除](https://github.com/retail-oukaku/flutter_study/pull/17/commits/86561e3a131888d1c4ae913ae84fb8b575142534)

2023-06-15 00:10 UTC, retail-oukaku commented on lib/kadai4/barcode_scan_page.dart
> +                      alignment: Alignment.center,
Centerに修正

2023-06-15 05:40 UTC, MinatoIshiwata commented on lib/extensions/string_extension.dart
> +    if (length != 13) {
マジックナンバではなく命名した数字にしましょう🙋

2023-06-15 05:40 UTC, MinatoIshiwata commented on lib/extensions/string_extension.dart
> +    var isbn = substring(3, 12);
マジックナンバではなく命名した数字にしましょう🙋

2023-06-15 05:40 UTC, MinatoIshiwata commented on lib/extensions/string_extension.dart
> +    if (sum%11 == 10) {
マジックナンバではなく命名した数字にしましょう🙋

2023-06-15 05:40 UTC, MinatoIshiwata commented on lib/extensions/string_extension.dart
> +      isbn += (sum%11).toString();
マジックナンバではなく命名した数字にしましょう🙋

2023-06-16 01:01 UTC, MinatoIshiwata approved these changes
@retail-oukaku 
1点だけ、Androidのカメラのパーミッションだけ修正をお願いいたします🙋
ご確認のほどよろしくお願いいたします。

2023-06-16 01:21 UTC, retail-oukaku commented
> 
修正しました。
[androidのカメラ権限を追加](https://github.com/retail-oukaku/flutter_study/pull/17/commits/3191631c3b76d88d2b940ec5fb1ec6a6f5bf453a)

2023-06-19 17:11 UTC, MinatoIshiwata commented on lib/kadai4/barcode_scan_page.dart
> +  void showAlertDialog() {
こちらもプライベートにしてください🙋

2023-06-19 17:12 UTC, MinatoIshiwata commented on lib/kadai4/barcode_scan_page.dart
> +  Future<void> scanBarcodeNormal() async {
こちらもプライベートにしてください🙋

2023-06-19 17:14 UTC, MinatoIshiwata requested changes
3点コメントいたしました。
ご確認のほどよろしくお願いいたします。

2023-06-21 15:29 UTC, MinatoIshiwata approved these changes
LGTM

2023-06-21 23:29 UTC, merged