Feature/kadai5
retail-oukaku/flutter_study pull request #20
Opened 2023-06-16 06:48 UTC by retail-oukaku

編集中

2023-06-19 02:26 UTC, retail-oukaku commented
Freezedを使用しているため、まず補正を閉じてからPRを再開します。

2023-06-19 04:30 UTC, retail-oukaku commented
Freezedを削除しました、reopenします。

2023-06-19 17:21 UTC, MinatoIshiwata commented on lib/kadai5/repository_detail_page.dart
> +        if (snapshot.connectionState == ConnectionState.done) {
snapshot.connectionStateはswitchで管理したほうが良いかと思います🙋

2023-06-19 17:21 UTC, MinatoIshiwata commented on lib/kadai5/repository_detail_page.dart
> +          return _buildBody(snapshot.data!);
force-unwrapではなく事前にチェックするように変更をお願い致します。

2023-06-19 17:22 UTC, MinatoIshiwata commented on lib/kadai5/repository_detail_page.dart
> +            ) : const Text(''),
if文で処理いただいたほうがよいかと思います。

2023-06-19 17:23 UTC, MinatoIshiwata commented on lib/kadai5/repository_detail_page.dart
> +        ) :const Text('null'),
こちらもif文で処理いただいたほうがよいかと思います🙋

2023-06-19 17:24 UTC, MinatoIshiwata commented on lib/kadai5/repository_detail_page.dart
> +      child: Row (
```suggestion
      child: Row(
```
不要なスペースです。

2023-06-19 17:27 UTC, MinatoIshiwata commented on lib/kadai5/repository_detail_page.dart
> +        model.subscribers_count.toString(),),);
こちらもう少し整理されたほうが良いかと思います。

2023-06-19 17:31 UTC, MinatoIshiwata commented on lib/kadai5/repository_list_page.dart
> +            ) :const Text('null'),
こちらもif文で処理いただいたほうが良いかと思います🙋

2023-06-19 17:32 UTC, MinatoIshiwata commented on lib/kadai5/search_user_page.dart
> +          child:GestureDetector(
スペースがないのでフォーマット見直してください。

2023-06-19 17:32 UTC, MinatoIshiwata commented on lib/kadai5/search_user_page.dart
> +            }
早期リターンのほうがネストが減ると思います🙋

2023-06-19 17:33 UTC, MinatoIshiwata requested changes
何点かコメントいたしました。
ご確認のほどよろしくお願いいたします。

2023-06-20 05:00 UTC, retail-oukaku commented on lib/kadai5/repository_detail_page.dart
> +          return _buildBody(snapshot.data!);
[指摘の対応](https://github.com/retail-oukaku/flutter_study/pull/20/commits/0c08dcd51d948eaf0cb7765b123017ced4a65425)
修正しました。

2023-06-20 05:01 UTC, retail-oukaku commented on lib/kadai5/repository_detail_page.dart
> +        if (snapshot.connectionState == ConnectionState.done) {
[指摘の対応：switchで管理に修正](https://github.com/retail-oukaku/flutter_study/pull/20/commits/eabded39a26cda2672a74d6ca6344ab9003fc14d)
switchでに修正しました。

2023-06-20 05:01 UTC, retail-oukaku commented on lib/kadai5/repository_detail_page.dart
> +            ) : const Text(''),
[指摘の対応：switchでに修正](https://github.com/retail-oukaku/flutter_study/pull/20/commits/29dfdba2072c91212f8b671502c639bc08c83549)
修正しました。

2023-06-20 05:02 UTC, retail-oukaku commented on lib/kadai5/repository_detail_page.dart
> +        ) :const Text('null'),
[指摘の対応：nullのチェック修正](https://github.com/retail-oukaku/flutter_study/pull/20/commits/9d8a45b83031ab1e19b86023f792046bac20862c)
修正しました。

2023-06-20 05:02 UTC, retail-oukaku commented on lib/kadai5/repository_list_page.dart
> +            ) :const Text('null'),
[指摘の対応：nullのチェック修正](https://github.com/retail-oukaku/flutter_study/pull/20/commits/3b8bff6b30944963cb0f72461dc479c4326d7f42)
修正しました。

2023-06-20 05:03 UTC, retail-oukaku commented on lib/kadai5/repository_detail_page.dart
> +      child: Row (
[spaceを修正](https://github.com/retail-oukaku/flutter_study/pull/20/commits/026ec4a07742416f1940f85d3f426eeaa6b7640d)
修正しました。

2023-06-20 05:04 UTC, retail-oukaku commented on lib/kadai5/search_user_page.dart
> +            }
[ネストが減るため](https://github.com/retail-oukaku/flutter_study/pull/20/commits/3d87f2f8867cd0484fa95af3d6542e406cbd2a7c)
修正しました。

2023-06-20 05:11 UTC, retail-oukaku commented on lib/kadai5/search_user_page.dart
> +          child:GestureDetector(
[spaceを追加](https://github.com/retail-oukaku/flutter_study/pull/20/commits/25003f6de4ed1b9549021eb9c26b229318f67ad6)
修正しました。

2023-06-21 01:58 UTC, retail-oukaku commented on lib/kadai5/repository_detail_page.dart
> +        model.subscribers_count.toString(),),);
[delete widget list](https://github.com/retail-oukaku/flutter_study/pull/20/commits/68807b6aebe7a0c1dbe10b227c639d9474e47df1)
修正しました。

2023-06-21 15:31 UTC, MinatoIshiwata commented on lib/kadai5/repository_detail_page.dart
> +            child: Icon(icon),
IconWidgetにサイズ変更プロパティがありますのでそちらをご利用ください

2023-06-21 15:32 UTC, MinatoIshiwata commented on lib/kadai5/search_user_page.dart
> +        const Text(''),
こちら不要かと思います

2023-06-22 00:58 UTC, retail-oukaku commented on lib/kadai5/repository_detail_page.dart
> +            child: Icon(icon),
[iconのsizeに修正](https://github.com/retail-oukaku/flutter_study/pull/20/commits/14dcb94311737b0afcee781495a4360cf77b2280)
修正しました。

2023-06-22 01:02 UTC, retail-oukaku commented on lib/kadai5/search_user_page.dart
> +        const Text(''),
[指摘の修正](https://github.com/retail-oukaku/flutter_study/pull/20/commits/9fda237f57d6c85007c752c16cc70aca1b1c193a)
削除しました。

2023-06-22 05:52 UTC, MinatoIshiwata approved these changes
LGTM

2023-06-22 05:53 UTC, merged